name: CI
run-name: >
  CI (${{ github.event_name }})
  ${{ github.event_name == 'pull_request' && format('PR#{0}', github.event.number) || '' }}

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: 📘 docs
    uses: ./.github/workflows/step_docs.yaml

  pass:
    name: ✅ Pass
    needs: [ docs ]
    runs-on: ubuntu-latest
    steps:
      - name: Check all CI jobs
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    if: always()
